# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [48]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
import numpy as np

A = np.arange(1, 16).reshape(3,5)

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
import numpy as np

B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2

resultof_multiplication = B - C

resultof_multiplication = B * C

resultof_matrix_multiplication = B @ C

print("Matrix B:")
print(B)
print("\nMatrix C:")
print(C)
print("\nElementwise Subtraction (B - C):")
print(resultof_multiplication)
print("\nElementwise Multiplication (B * C):")
print(resultof_multiplication)
print("\nMatrix Multiplication (B @ C):")
print(resultof_matrix_multiplication)

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementwise Subtraction (B - C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Elementwise Multiplication (B * C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication (B @ C):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [9]:
import numpy as np

B = np.arange(1, 10).reshape(3, 3)
print(B)

exp_matrix_elementwise = np.exp (B)
print(exp_matrix_elementwise)

min_value_matrix = np.min(B)
print(min_value_matrix)

min_value_each_column = np.min(B, axis=0)
print(min_value_each_column)

min_index_whole = np.argmin(B)
print(min_index_whole)

min_index_each_row = np.argmin(B, axis=1)
print(min_index_each_row)

total_sum_matrix = np.sum(B)
print(total_sum_matrix)

mean_each_column = np.mean(B, axis=0)
print(mean_each_column)

median_each_column = np.median(B, axis=0)
print(median_each_column)





[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 2 3]
0
[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [10]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [11]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

print("Matris A:")
print(A)

row = A[1]
print("\nA[1] returns the row with index 1:")
print(row)

element = A[1, 0]
print("\nA[1, 0] returns the element at row 1, column 0:")
print(element)

Matris A:
[[1 2]
 [3 4]]

A[1] returns the row with index 1:
[3 4]

A[1, 0] returns the element at row 1, column 0:
3


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [5]:
A

array([[1, 2],
       [3, 4]])

In [7]:
for i in A:
    print(i)

[1 2]
[3 4]


In [9]:
import numpy as np

A = np.array([[1, 2], [3, 4]])


for element in np.nditer(A):
    print(element)

1
2
3
4


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [40]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [10]:
import numpy as np

a = np.arange(30)    # 1D array from 0 to 29
b = a.reshape((2, 3, -1))  # Reshape it to a 3D array

print("1D array 'a':")
print(a)
print()

print("3D array 'b' after reshaping:")
print(b)

1D array 'a':
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

3D array 'b' after reshaping:
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [11]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [2]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [43]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [1]:
import numpy as np
x = np.array([4, 3])
# (a) Dimension av vektorn x
dimension = x.shape
print("Dimension of x:", dimension)

# (b) Beräkna 5x
result_b = 5 * x
print("5x:", result_b)

# (c) Beräkna 3x
result_c = 3* x
print("3x:", result_c)

# (d) Beräkna 5x + 3x
result_d = 5 * x + 3 * x
print("5x + 3x:", result_d)

# (e) Beräkna 8x
result_e = 8 * x
print("8x:", result_e)

# (f) Beräkna 4x -x 
result_f = 4 * x -x 
print("4x - x:", result_f)

# (g) Transpose x and check dimension
x_T = x.T
dimension_g = x_T.shape
print("Transpose of x(x^T):", x_T)
print("dimension of x^T:", dimension_g)

# (h) är x + x^T definerat 
result_h = x + x_T
print("x+x^T:", result_h)

# (i) Beräkna ||x||
result_i = np.linalg.norm(x)
print("||x||:", result_i )





Dimension of x: (2,)
5x: [20 15]
3x: [12  9]
5x + 3x: [32 24]
8x: [32 24]
4x - x: [12  9]
Transpose of x(x^T): [4 3]
dimension of x^T: (2,)
x+x^T: [8 6]
||x||: 5.0


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [6]:
import numpy as np

# Definiera matriserna
A = np.array([[2, 1, -1],
              [1, -1, 1]])

B = np.array([[4, -2, 1],
              [2, -4, -2]])

C = np.array([[1, 2],
              [2, 1]])

D = np.array([[3, 4],
              [4, 3]])

E = np.array([[1],
              [2]])

I = np.array([[1, 0],
              [0, 1]])

# (a) 2A
result_a = 2 * A
print("(a) 2A:\n", result_a)


# (b) B - 2A
result_b = B - 2 * A
print("\n(b) B - 2A:\n", result_b)


# (c) 3C - 2E
result_c = 3 * C - 2 * E
print("\n(c) 3C - 2E:\n", result_c)


# (d) 2D - 3C
result_d = 2 * D - 3 * C
print("\n(d) 2D - 3C:\n", result_d)


# (e) D^T + 2D
result_e = D.T + 2 * D
print("\n(e) D^T + 2D:\n", result_e)


# (f) 2C^T - 2D^T
result_f = 2 * C.T - 2 * D.T
print("(f) 2C^T - 2D^T:\n", result_f)


# (g) A^T - B
A_T = A.T
if A_T.shape == B.shape:
    result_g = A_T - B
    print("\n(g) A^T - B:\n", result_g)
else:    
    print("\n(g) A^T - B är inte definierad eftersom dimensionerna inte matchar.")


# (h) AC
# result_h = np.dot(A, C)
# print("\n(h) AC:\n", result_h)
if A.shape[1] == C.shape[0]:
    result_h = np.dot(A, C)
    print("\n(h) AC:\n", result_h)
else:
    print("\n(h) AC är inte definierad eftersom dimensionerna inte matchar.")

# (i) CD
result_i = np.dot(C, D)
print("\n(i) CD:\n", result_i)


# (j) CB
result_j = np.dot(C, B)
print("\n(j) CB:\n", result_j)


# (k) CI
result_k = np.dot(C, I)
print("\n(k) CI:\n", result_k)


# (l) AB^T
result_l = np.dot(A, B.T)
print("\n(l) AB^T:\n", result_l)


import numpy as np

# Uppgift 10.2.2
# Definiera matrisen A
A = np.array([[2, 3, 4],
              [5, 4, 1]])

# Beräkna AA^T
AAT = np.dot(A, A.T)
print("Uppgift 10.2.2: AA^T\n", AAT)

# Uppgift 10.2.3
# Definiera matriserna A, B och C
A = np.array([[1, 2],
              [2, 4]])

B = np.array([[2, 1],
              [1, 3]])

C = np.array([[4, 3],
              [0, 2]])

# Beräkna AB och AC
AB = np.dot(A, B)
AC = np.dot(A, C)

# Kontrollera om AB == AC och B == C
print("\nUppgift 10.2.3:")
print("AB:\n", AB)
print("AC:\n", AC)

# Kontrollera om AB == AC
if np.array_equal(AB, AC):
    print("AB är lika med AC")
else:
    print("AB är inte lika med AC")

# Kontrollera om B == C
if np.array_equal(B, C):
    print("B är lika med C")
else:
    print("B är inte lika med C")

(a) 2A:
 [[ 4  2 -2]
 [ 2 -2  2]]

(b) B - 2A:
 [[ 0 -4  3]
 [ 0 -2 -4]]

(c) 3C - 2E:
 [[ 1  4]
 [ 2 -1]]

(d) 2D - 3C:
 [[3 2]
 [2 3]]

(e) D^T + 2D:
 [[ 9 12]
 [12  9]]
(f) 2C^T - 2D^T:
 [[-4 -4]
 [-4 -4]]

(g) A^T - B är inte definierad eftersom dimensionerna inte matchar.

(h) AC är inte definierad eftersom dimensionerna inte matchar.

(i) CD:
 [[11 10]
 [10 11]]

(j) CB:
 [[  8 -10  -3]
 [ 10  -8   0]]

(k) CI:
 [[1 2]
 [2 1]]

(l) AB^T:
 [[5 2]
 [7 4]]
Uppgift 10.2.2: AA^T
 [[29 26]
 [26 42]]

Uppgift 10.2.3:
AB:
 [[ 4  7]
 [ 8 14]]
AC:
 [[ 4  7]
 [ 8 14]]
AB är lika med AC
B är inte lika med C


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [4]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [14]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [15]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [9]:
import numpy as np

v1 = np.arange(4)

v2_view = v1[-2:]

# kopia
v2_copy = v1[-2:].copy()

# 
print("v1.base:", v1.base)  
print("v2_view.base:", v2_view.base) 
print("v2_copy.base:", v2_copy.base)  

v1.base: None
v2_view.base: [0 1 2 3]
v2_copy.base: None
